name: Download Ubuntu Tar

on: 
  push:
    branches:
      - main

jobs:
  download-ubuntu:     
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Ubuntu tar file
      run: |
           curl -L -o ubuntu.tar.gz https://releases.ubuntu.com/20.04/ubuntu-20.04.6-live-server-amd64.iso
           tar -xzf ubuntu.tar.gz -C ./ubuntu
